### ISSUE TITLE
Doesn't extract some classes

### ISSUE THREAD

**Issue by ahstro** [bitstrider/css-extractor#1]
Doesn't extract `.field` nor `.is-horizontal` from this structure, taken from [Bulma](https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css)

```css
@media screen and (min-width: 769px), print {
  .field.is-horizontal {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
  }
}
```
